export enum OrderStatus {
  PICKUP_PENDING_OR_BRANCH_ASSIGNMENT_PENDING = 1,
  ASSIGNED_PICKUP_BOY = 2,
  PICKUP_COMPLETED_BY_PICKUP_BOY = 3,
  ITEMS_RECEIVED_AT_BRANCH = 4,
  WORKSHOP_ASSIGNED = 5,
  WORKSHOP_RECEIVED_ITEMS = 6,
  WORKSHOP_WORK_IN_PROGRESS = 7,
  WORKSHOP_WORK_IS_COMPLETED = 8,
  ORDER_COMPLETED_AND_RECEIVED_AT_BRANCH = 9,
  DELIVERY_BOY_ASSIGNED_AND_READY_FOR_DELIVERY = 10,
  DELIVERED = 11,
  CANCELLED_BY_ADMIN = 12,
  CANCELLED_BY_CUSTOMER = 13,
}

export enum CustomerOrderStatus {
  WAITING_FOR_PICKUP = 'Waiting For Pickup',
  PICKUP_COMPLETE = 'Pickup Completed',
  IN_PROCESS = 'In Process',
  READY_FOR_DELIVERY = 'Ready For Delivery',
  DELIVERED = 'Delivered',
  ORDER_CANCELLED_BY_ADMIN = 'Order Cancelled By Admin',
  ORDER_CANCELLED_BY_CUSTOMER = 'Order Cancelled By Customer',
}

export enum WorkshopOrderStatus {
  ORDER_RECEIVED = 'Order Received',
  IN_PROGRESS = 'In Progress',
  COMPLETED = 'Completed',
}
